name: 'tuva_ccsr'
version: '0.2.6'
config-version: 2

profile: default


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"



vars:
    condition: >
        {% if var('ccsr_condition_override',none) is not none %}{{var('ccsr_condition_override')}}
        {%- elif var('core_condition_override',none) is not none %}{{var('core_condition_override')}}
        # {%- else %}{{ref('claims_preprocessing__condition')}}
        {%- endif %}
    # procedure: >
    #     {% if var('ccsr_procedure_override',none) is not none %}{{var('ccsr_procedure_override')}}
    #     {%- elif var('core_procedure_override',none) is not none %}{{var('core_procedure_override')}}
    #     {%- else %}{{ref('claims_preprocessing__procedure')}}
    #     {%- endif %}
    
    # ccsr_condition_override: "{{ref('condition')}}"

    ccsr_condition_override: "(select * from medicare_saf.core.condition limit 100)"
    dxccsr_version: "2023.1"