name: 'tuva_ccsr'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.10.0"

profile: default


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
    tuva_ccsr:
        dxccsr_v2023_1_body_systems:
            +post-hook: "{{ the_tuva_project.load_package_seed('tuva_ccsr', 'ccsr', 'dxccsr_v2023_1_body_systems.csv.gz') }}"
        dxccsr_v2023_1_cleaned_map:
            +post-hook: "{{ the_tuva_project.load_package_seed('tuva_ccsr', 'ccsr', 'dxccsr_v2023_1_cleaned_map.csv.gz') }}"
        prccsr_v2023_1_cleaned_map:
            +post-hook: "{{ the_tuva_project.load_package_seed('tuva_ccsr', 'ccsr', 'prccsr_v2023_1_cleaned_map.csv.gz') }}"


vars:

    # These vars enable the wide tables - disabling will exclude wide tables from dbt runs
    wide_condition_enabled: True
    wide_procedure_enabled: True

    # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
    record_type: "ip"

    # CCSR Version numbers from HCUP
    dxccsr_version: "'2023.1'"
    prccsr_version: "'2023.1'"
